####################################################################################
#                                  Server                                          #
####################################################################################
server:
  port: 5656
  servlet:
    context-path: /demo
  error:
    path: /error
    # always | never
    include-stacktrace: never
    whitelabel.enabled: true

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
####################################################################################
#                                    DEFAULT                                       #
####################################################################################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  main:
    allow-bean-definition-overriding: true
  # charset UTF-8 강제설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: loc

#### Custom 속성 ####
# 버전정보
demo.info.version: 1.0.0

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
####################################################################################
#                                    LOC                                           #
####################################################################################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  profiles: loc
